### ISSUE TITLE
[FEATURE] 추가 기능 구현 

### ISSUE THREAD

**Issue by ARONGLEE** [ARONGLEE/pre-onboarding-10th-3-9#1]
### 🏊 Todo

- [x] 사용자가 input에 타이핑을 하면 제공된 search api를 통해 받은 아이템들이 dropdown에 보여질 수 있도록 InputTodo 컴포넌트에 추천 기능을 구현
- [x] 디자인 가이드(Figma)를 참고해서 InputTodo의 디자인 수정 및 dropdown을 새로 만들기
- [x] Input에 500ms로 debounce를 적용
- [ ] Dropdown에 추천된 아이템들이 처음에 10개가 나올 수 있도록 하고, 아이템이 더 있으면 무한 스크롤로 최대 10개씩 받아올 수 있도록 구현
- [x] Dropdown에서 아이템 하나를 선택하면, input의 value는 초기화가 되고 아이템이 리스트에 추가되도록 구현

### 💬 Additional information
- Bootstrap이나 Ant Design, tailwindcss와 같은 UI kit은 사용하지 않고 구현
- (선택항목) Jest나 Cypress등을 이용해 테스트코드 작성
